---
title: "data exploration"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r, echo=FALSE, warning=FALSE, cache.lazy=FALSE}
# load libraries 

library(tidyverse)
library(ggpubr)
library(patchwork)
library(ggsci)
library(readxl)

```


```{r, echo=FALSE, warning=FALSE}
# read data

data <- read_excel("data/NGSscoping_db_final.xlsx")

```

```{r, echo=FALSE, fig.width = 6 ,warning=FALSE}
# stacked histogram of sample size by compartment

stacked_hist_sample_size_compartment <-
data |>
  mutate(ARACHNIDA_SAMPLE_SIZE = as.character(ARACHNIDA_SAMPLE_SIZE)) |>
  mutate(INSECTA_SAMPLE_SIZE = as.character(INSECTA_SAMPLE_SIZE)) |>
  select(ABIOTIC_SAMPLE_SIZE, HUM_SAMPLE_SIZE, POULTRY_SAMPLE_SIZE, LIVESTOCK_SAMPLE_SIZE, WILDLIFE_SAMPLE_SIZE, PET_SAMPLE_SIZE, ARACHNIDA_SAMPLE_SIZE, INSECTA_SAMPLE_SIZE, BIOTIC_SAMPLE_SIZE, ENV_DOMAIN) |>
  pivot_longer(cols = c(ABIOTIC_SAMPLE_SIZE, HUM_SAMPLE_SIZE, POULTRY_SAMPLE_SIZE, LIVESTOCK_SAMPLE_SIZE, WILDLIFE_SAMPLE_SIZE, PET_SAMPLE_SIZE, ARACHNIDA_SAMPLE_SIZE, INSECTA_SAMPLE_SIZE, BIOTIC_SAMPLE_SIZE, ENV_DOMAIN), names_to = "compartment" , values_to = "sample size") |>
  separate(col = "compartment", into = c("compartment", NA, NA), sep = "_", extra = "drop") |>
  mutate(`sample size` = as.numeric(`sample size`)) |>
  mutate(compartment = ifelse(compartment == "HUM", "HUMAN", compartment)) |> ggplot(aes(`sample size`, group = compartment, fill = compartment)) + 
  geom_histogram(bins = 50) + 
  scale_x_log10() + 
  xlab("Sample size") + 
  ylab("count") + 
  # facet_wrap(~compartment, nrow = 4) + 
  ggthemes::theme_clean() + 
  scale_fill_viridis_d()

stacked_hist_sample_size_compartment
# stacked_hist_sample_size_compartment |>
#   ggsave(filename = "figures/stacked_histogram_sample_size_by_compartment.pdf", width=8)
```

```{r, echo=FALSE, fig.width = 8 ,warning=FALSE}

#  sample size per compartment x study aim

hist_sample_size_compartment_aim <-
data |>
  mutate(ARACHNIDA_SAMPLE_SIZE = as.character(ARACHNIDA_SAMPLE_SIZE)) |>
  mutate(INSECTA_SAMPLE_SIZE = as.character(INSECTA_SAMPLE_SIZE)) |>
  select(STUDY_AIM_1, ABIOTIC_SAMPLE_SIZE, HUM_SAMPLE_SIZE, POULTRY_SAMPLE_SIZE, LIVESTOCK_SAMPLE_SIZE, WILDLIFE_SAMPLE_SIZE, PET_SAMPLE_SIZE, ARACHNIDA_SAMPLE_SIZE, INSECTA_SAMPLE_SIZE, BIOTIC_SAMPLE_SIZE) |>
  pivot_longer(cols = c(ABIOTIC_SAMPLE_SIZE, HUM_SAMPLE_SIZE, POULTRY_SAMPLE_SIZE, LIVESTOCK_SAMPLE_SIZE, WILDLIFE_SAMPLE_SIZE, PET_SAMPLE_SIZE, ARACHNIDA_SAMPLE_SIZE, INSECTA_SAMPLE_SIZE, BIOTIC_SAMPLE_SIZE), names_to = "compartment" , values_to = "sample size") |>
  separate(col = "compartment", into = c("compartment", NA, NA), sep = "_", extra = "drop") |>
  mutate(`sample size` = as.numeric(`sample size`)) |>
  mutate(compartment = ifelse(compartment == "HUM", "HUMAN", compartment)) |>
ggplot(aes(`sample size`, group = STUDY_AIM_1, fill = STUDY_AIM_1)) + 
  geom_histogram(bins = 20) + 
  scale_x_log10() + 
  xlab("Sample size") + 
  ylab("count") + 
  facet_wrap(~compartment, nrow = 4) +
  ggthemes::theme_clean() + 
  scale_fill_rickandmorty() + 
  theme(legend.position = "top")

hist_sample_size_compartment_aim

hist_sample_size_compartment_aim <-
  ggsave(filename = "figures/histogram_sample_size_by_compartment_colored_by_study_aim_Nov13.pdf", width=14, height = 8)

```

```{r, echo=FALSE, fig.width = 8 ,warning=FALSE}

hist_sample_size_compartment_agent_type <-
data |>
  mutate(ARACHNIDA_SAMPLE_SIZE = as.character(ARACHNIDA_SAMPLE_SIZE)) |>
  mutate(INSECTA_SAMPLE_SIZE = as.character(INSECTA_SAMPLE_SIZE)) |>
  select(ABIOTIC_SAMPLE_SIZE, HUM_SAMPLE_SIZE, POULTRY_SAMPLE_SIZE, LIVESTOCK_SAMPLE_SIZE, WILDLIFE_SAMPLE_SIZE, PET_SAMPLE_SIZE, ARACHNIDA_SAMPLE_SIZE, INSECTA_SAMPLE_SIZE, BIOTIC_SAMPLE_SIZE, AGENT_TYPE) |>
  pivot_longer(cols = c(ABIOTIC_SAMPLE_SIZE, HUM_SAMPLE_SIZE, POULTRY_SAMPLE_SIZE, LIVESTOCK_SAMPLE_SIZE, WILDLIFE_SAMPLE_SIZE, PET_SAMPLE_SIZE, ARACHNIDA_SAMPLE_SIZE, INSECTA_SAMPLE_SIZE, BIOTIC_SAMPLE_SIZE), names_to = "compartment" , values_to = "sample size") |>
  separate(col = "compartment", into = c("compartment", NA, NA), sep = "_", extra = "drop") |>
  mutate(`sample size` = as.numeric(`sample size`)) |>
  mutate(compartment = ifelse(compartment == "HUM", "HUMAN", compartment)) |>
  mutate(AGENT_TYPE = ifelse(str_detect(AGENT_TYPE, "bacterium") == TRUE, "bacterium", AGENT_TYPE)) |>
     mutate(AGENT_TYPE = ifelse(str_detect(AGENT_TYPE, "virus") == TRUE, "virus", AGENT_TYPE)) |>
ggplot(aes(`sample size`, group = AGENT_TYPE, fill = AGENT_TYPE)) + 
  geom_histogram(bins = 20) + 
  scale_x_log10() + 
  xlab("Sample size") + 
  ylab("count") + 
  facet_wrap(~compartment, nrow = 4) +
  ggthemes::theme_clean() + 
  # scale_fill_manual(values = c("skyblue2", "royalblue3", "green4", "lightpink2", "orange1")) + 
  scale_fill_ordinal()+
  theme(legend.position = "bottom")


hist_sample_size_compartment_agent_type
hist_sample_size_compartment_agent_type |>
  ggsave(filename = "figures/histogram_sample_size_by_compartment_colored_by_agent_type_Nov13.pdf", width=10, height = 8)


hist_sample_size_by_agent_type_only <-
data |>
  mutate(ARACHNIDA_SAMPLE_SIZE = as.character(ARACHNIDA_SAMPLE_SIZE)) |>
  mutate(INSECTA_SAMPLE_SIZE = as.character(INSECTA_SAMPLE_SIZE)) |>
  select(ABIOTIC_SAMPLE_SIZE, HUM_SAMPLE_SIZE, POULTRY_SAMPLE_SIZE, LIVESTOCK_SAMPLE_SIZE, WILDLIFE_SAMPLE_SIZE, PET_SAMPLE_SIZE, ARACHNIDA_SAMPLE_SIZE, INSECTA_SAMPLE_SIZE, BIOTIC_SAMPLE_SIZE, AGENT_TYPE) |>
  pivot_longer(cols = c(ABIOTIC_SAMPLE_SIZE, HUM_SAMPLE_SIZE, POULTRY_SAMPLE_SIZE, LIVESTOCK_SAMPLE_SIZE, WILDLIFE_SAMPLE_SIZE, PET_SAMPLE_SIZE, ARACHNIDA_SAMPLE_SIZE, INSECTA_SAMPLE_SIZE, BIOTIC_SAMPLE_SIZE), names_to = "compartment" , values_to = "sample size") |>
  separate(col = "compartment", into = c("compartment", NA, NA), sep = "_", extra = "drop") |>
  mutate(`sample size` = as.numeric(`sample size`)) |>
  mutate(compartment = ifelse(compartment == "HUM", "HUMAN", compartment)) |>
  mutate(AGENT_TYPE = ifelse(str_detect(AGENT_TYPE, "bacterium") == TRUE, "bacterium", AGENT_TYPE)) |>
     mutate(AGENT_TYPE = ifelse(str_detect(AGENT_TYPE, "virus") == TRUE, "virus", AGENT_TYPE)) |>
ggplot(aes(`sample size`, group = AGENT_TYPE, fill = AGENT_TYPE)) + 
  geom_histogram(bins = 20) + 
  scale_x_log10() + 
  xlab("Sample size") + 
  ylab("count") + 
  ggthemes::theme_clean() + 
  # scale_fill_manual(values = c("skyblue2", "royalblue3", "green4", "lightpink2", "orange1")) + 
  scale_fill_ordinal()+
  theme(legend.position = "bottom")

hist_sample_size_by_agent_type_only
hist_sample_size_by_agent_type_only |>
  ggsave(filename = "figures/histogram_sample_size_colored_by_agent_type.pdf", width=8, height = 8)

```

# Zoonotic agent

```{r, echo=FALSE, fig.width = 6 ,warning=FALSE}


discrete_palettes <- list(
  RColorBrewer::brewer.pal(8, "Paired")
)

data |> 
  group_by(AGENT_TYPE) |>
  summarise(count = n()) |>
  ggplot(aes(count, fill = AGENT_TYPE, group = AGENT_TYPE)) + 
  geom_histogram(bins = 50) + 
  scale_fill_discrete(type = discrete_palettes) + 
ggthemes::theme_clean()

n_studies_dist_by_agent_type <- 
data |>
  group_by(AGENT_TYPE, ZOONOTIC_AGENT) |>
  summarise(count = n()) |>
  group_by(AGENT_TYPE, count) |>
  summarise(n_studies = n()) |>
  ggplot(aes(count, n_studies, fill = AGENT_TYPE)) + geom_col() + facet_wrap(~AGENT_TYPE, nrow=2 ) + 
  scale_fill_discrete(type = discrete_palettes) + 
  ggthemes::theme_clean() + 
  theme(legend.position = "none") + xlab("Number of species") + ylab("Number of studies")

n_studies_dist_by_agent_type

# n_studies_dist_by_agent_type |>
#   ggsave(filename = "figures/number_of_studies_by_agent_type.pdf", width = 7, height = 4)
```

# Number of studies by sampling range 

```{r, echo=FALSE, fig.width = 6 ,warning=FALSE}

# not sure how to treat "N/S" in SAMPLING_YEAR.S. 

discrete_palettes <- list(
  RColorBrewer::brewer.pal(8, "Paired")
)

n_studies_by_sampling_range_and_agent_type <- 
data |> 
  # separate(SAMPLING_YEAR.S., sep = "-", into = c("START", "END", NA), extra="drop", fill = "warn", remove = FALSE) |>
  # mutate(END = ifelse(is.na(END), START, END)) |>
  # mutate(START = ifelse(START == "N/S", NA, START)) |>
  # mutate(END = ifelse(START == "N/S", NA, END)) |>
  # mutate(START = as.numeric(START)) |>
  # mutate(END = as.numeric(END)) |> 
  mutate(SAMPLING_RANGE = as.numeric(LAST_SAMPLE_DATE)-as.numeric(FIRST_SAMPLE_DATE)) |>
  mutate(SAMPLING_RANGE = ifelse(is.na(SAMPLING_RANGE), -5, SAMPLING_RANGE)) |> 
  # group_by(AGENT_TYPE, SAMPLING_RANGE) |>
  # summarise(count = n()) >
  ggplot(aes(SAMPLING_RANGE, fill = AGENT_TYPE)) +
  # geom_bar() +
  geom_histogram(bins=20) + 
facet_wrap(~AGENT_TYPE, nrow=2 ) +   # ggplot(aes(SAMPLING_RANGE, count, fill = AGENT_TYPE)) + geom_col() + 
  ggthemes::theme_clean() + 
  scale_fill_discrete(type = discrete_palettes) + theme(legend.position = "none")

n_studies_by_sampling_range_and_agent_type

n_studies_by_sampling_range_and_agent_type |>
  ggsave(filename = "figures/stacked_histogram_number_of_studies_and_sampling_range.pdf", width = 8)

```



```{r, echo=FALSE, fig.width = 8 ,warning=FALSE}

Assembly_license <-
data |>
  group_by(`ASSEMBLY/MAPPING_LICENSE`) |>
  summarise(`Assembly/Mapping` = n()) |>
  rename(LICENSE = `ASSEMBLY/MAPPING_LICENSE`)
  
software_license <-
data |>
  group_by(PHYLO_LICENSE) |>
  summarise(Phylo = n()) |>
  rename(LICENSE = PHYLO_LICENSE) |>
  left_join(Assembly_license) |>
  pivot_longer(cols = c(Phylo, `Assembly/Mapping`), names_to = "Software")

software_license |>
  ggplot(aes(LICENSE, value, fill = Software)) + geom_col(stat = "identity", position = position_dodge()) +   scale_fill_manual(values = c("turquoise3", "royalblue1")) + 
  ggthemes::theme_clean()

```

```{r, echo=FALSE, fig.width = 8 ,warning=FALSE}


discrete_palettes <- list(
  RColorBrewer::brewer.pal(8, "Spectral")
)


data |>
  group_by(PHYLO_RESULTS, PHYLO_MODEL) |>
  summarise(count = n()) |>
  separate(PHYLO_MODEL, sep = "\\+", into = c("m1", "m2", "m3")) |>
  pivot_longer(cols = c(m1, m2, m3), names_to = "model") |>
  group_by(PHYLO_RESULTS, value) |>
  summarise(freq = sum(count)) |>
  rename(PHYLO_MODEL = value) |>
  ungroup() |>
  complete(PHYLO_RESULTS, PHYLO_MODEL, fill = list(freq = 0)) |>
  filter(!(is.na(PHYLO_MODEL))) |>
  ggplot(aes(PHYLO_MODEL, freq, fill = PHYLO_RESULTS)) + geom_col(stat = "identity", position = position_dodge()) + ggthemes::scale_fill_pander() + ggthemes::theme_clean() + xlab("Phylo Model") + theme(legend.position="top",legend.justification="centre")

```

```{r}

study_sample_size_phylo_results <-
data |>
  mutate(ARACHNIDA_SAMPLE_SIZE = as.character(ARACHNIDA_SAMPLE_SIZE)) |>
  mutate(INSECTA_SAMPLE_SIZE = as.character(INSECTA_SAMPLE_SIZE)) |>
  select(PHYLO_RESULTS,
         HUM_SAMPLE_SIZE, 
         POULTRY_SAMPLE_SIZE, 
         LIVESTOCK_SAMPLE_SIZE, 
         WILDLIFE_SAMPLE_SIZE, 
         PET_SAMPLE_SIZE, 
         ARACHNIDA_SAMPLE_SIZE, 
         INSECTA_SAMPLE_SIZE, 
         `BIOTIC-ENV_SAMPLE_SIZE`) |>
  pivot_longer(cols = c(HUM_SAMPLE_SIZE, POULTRY_SAMPLE_SIZE, LIVESTOCK_SAMPLE_SIZE, WILDLIFE_SAMPLE_SIZE, PET_SAMPLE_SIZE, ARACHNIDA_SAMPLE_SIZE, INSECTA_SAMPLE_SIZE, `BIOTIC-ENV_SAMPLE_SIZE`), names_to = "compartment" , values_to = "sample size") |>
  mutate(`sample size` = as.numeric(`sample size`)) |>
  mutate(compartment = ifelse(compartment == "HUM", "HUMAN", compartment)) |> 
select(PHYLO_RESULTS, `sample size`) |>
  filter(!is.na(`sample size`)) |>
  filter(`sample size` > 0) |>
  ggplot(aes(`sample size`, fill = PHYLO_RESULTS)) + geom_histogram(bins = 30) + scale_x_log10() + ggthemes::scale_fill_pander() + ggthemes::theme_clean() + xlab("Sample size") + theme(legend.position="top",legend.justification="centre")

study_sample_size_phylo_results |>
  ggsave(filename = "figures/stacked_histogram_study_sample_size_phylo_results.pdf", width = 8)
```

